title: <p align="center"> Litvinov Sergey </p>

logo: "/images/logo.png?raw=true" # your photo (or logo) here

description:  # your text below (remove <br> elements if you don't need line breaks)
  <p align="center">
  <a href="pdf/Litvinov_Sergey.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sergey-litvinov/">LinkedIn</a> |
  <a href="https://github.com/LtvnSergey">GitHub</a>
  </p>
  
  <p align="justify">
  I'm pursing my goal to become great data scientist 
  <br><br>
  I am working with various Machine learning problems as well as Deep learning computer vision tasks - detection, segmentation, classification 
  <br><br>
  </p>

theme: jekyll-theme-minimal
google_analytics: G-T828GBHM8X # your Google Analytics tracking ID here
